# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
- script: 'sudo npm install gatsby -g'
  displayName: 'Install Gatsby'
- script: gatsby build
  displayName: 'Gatsby build'
- task: PublishBuildArtifacts@1
  displayName: 'Publish to drop'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/public/'
    ArtifactName: 'drop'
    publishLocation: 'Container'
